### ISSUE TITLE
interpreter choice 

### ISSUE THREAD

**Issue by yjftsjthsd-g** [jroimartin/sw#3]
I see that the shebang on sw was recently changed from `/bin/sh` to `/bin/bash`, and I'd like to request that this be reverted. The current version appears to be fully compatible between all Bourne-compatible shells, and there are systems where BASH isn't installed by default (mostly *BSD), so this reduces compatibility for no apparent gain. On systems using DASH (like Debian), `sh` should also be faster than `bash`, although I'll grant that in our use case a noticeable difference is unlikely.

In the event that switching to BASH really is desirable (it _does_ have features not found in vanilla Bourne shell, although we don't appear to be using them), it would be appreciated if we could use `#!/usr/bin/env bash`, which is more portable (again, *BSD doesn't put bash in /bin).

**Comment by jroimartin** [comment]
I totally agree, will revert it to /bin/sh. It always was my intention to keep sw free of bashisms. Actually, if we detect a bashism, the way to go is to change it to the POSIX equivalent.

Thanks for the report. I'll fix it today.

**Comment by jroimartin** [comment]
Fixed! I've tested it with /bin/sh pointing to /bin/dash and everything works as expected.
